"""Añadidos nuevos campos en recetas

Revision ID: 4f77563651bd
Revises: ef4fc7b378e9
Create Date: 2025-06-08 18:49:00.909644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f77563651bd'
down_revision = 'ef4fc7b378e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dificultad', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tiempo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('tiempo')
        batch_op.drop_column('dificultad')

    # ### end Alembic commands ###
