"""Modelos restantes añadidos

Revision ID: 66f02575287c
Revises: ed8bce6234c6
Create Date: 2025-05-15 05:51:37.627193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f02575287c'
down_revision = 'ed8bce6234c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergenos',
    sa.Column('id_alergeno', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_alergeno'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('subcategorias',
    sa.Column('id_subcategoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_subcategoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ingredientes',
    sa.Column('id_ingrediente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('alergeno_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alergeno_id'], ['alergenos.id_alergeno'], ),
    sa.PrimaryKeyConstraint('id_ingrediente'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('planificaciones',
    sa.Column('id_planificacion', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_planificacion')
    )
    op.create_table('favoritos',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id_receta'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_favorito'),
    sa.UniqueConstraint('usuario_id', 'receta_id', name='uq_usuario_receta_favorito')
    )
    op.create_table('planificacion_receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planificacion_id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['planificacion_id'], ['planificaciones.id_planificacion'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id_receta'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planificacion_id', 'dia', 'categoria_id', name='uq_planificacion_dia_categoria')
    )
    op.create_table('receta_alergeno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('alergeno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alergeno_id'], ['alergenos.id_alergeno'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id_receta'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receta_id', 'alergeno_id', name='uq_receta_alergeno')
    )
    op.create_table('receta_ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id_ingrediente'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id_receta'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receta_id', 'ingrediente_id', name='uq_receta_ingrediente')
    )
    op.create_table('receta_subcategoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('subcategoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id_receta'], ),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id_subcategoria'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receta_id', 'subcategoria_id', name='uq_receta_subcategoria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receta_subcategoria')
    op.drop_table('receta_ingrediente')
    op.drop_table('receta_alergeno')
    op.drop_table('planificacion_receta')
    op.drop_table('favoritos')
    op.drop_table('planificaciones')
    op.drop_table('ingredientes')
    op.drop_table('subcategorias')
    op.drop_table('alergenos')
    # ### end Alembic commands ###
