"""Crear modelos de Receta, Categoria y Region

Revision ID: ed8bce6234c6
Revises: 350f7f24c524
Create Date: 2025-05-07 22:02:03.867924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8bce6234c6'
down_revision = '350f7f24c524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('regiones',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_region'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('recetas',
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('preparacion', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regiones.id_region'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetas')
    op.drop_table('regiones')
    op.drop_table('categorias')
    # ### end Alembic commands ###
