"""Añadido reglas en cascada

Revision ID: ef4fc7b378e9
Revises: 66f02575287c
Create Date: 2025-05-21 02:46:49.338851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4fc7b378e9'
down_revision = '66f02575287c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredientes', schema=None) as batch_op:
        batch_op.drop_constraint('ingredientes_alergeno_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'alergenos', ['alergeno_id'], ['id_alergeno'], ondelete='SET NULL')

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('recetas_region_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('recetas_categoria_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('recetas_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id_categoria'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'regiones', ['region_id'], ['id_region'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id_usuario'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recetas_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id_usuario'])
        batch_op.create_foreign_key('recetas_categoria_id_fkey', 'categorias', ['categoria_id'], ['id_categoria'])
        batch_op.create_foreign_key('recetas_region_id_fkey', 'regiones', ['region_id'], ['id_region'])
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ingredientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ingredientes_alergeno_id_fkey', 'alergenos', ['alergeno_id'], ['id_alergeno'])

    # ### end Alembic commands ###
